### ISSUE TITLE
插件用不了啊

### ISSUE THREAD

**Issue by kymowang** [BlackHole1/autoFindXssAndCsrf#3]
先是显示不是从chrome商店安装的，然后我该用开发者模式安装crx解压的文件，倒是没有报错，但是按钮是灰色的。chrome: 版本 60.0.3112.90（正式版本） （64 位）@windows 10
![sp170810_114756](https://user-images.githubusercontent.com/3396402/29153739-d06aa074-7dc1-11e7-8597-52c2fca8712d.png)

**Comment by kymowang** [comment]
我明白了，这个插件是自动运行的啊。。。应该弄个开关才好

**Comment by BlackHole1** [comment]
因为最近较忙，开关功能回进行考虑的。谢谢支持
